"""Public database API boundary."""

from vibe_bt_03.database.api.manage import (
    DatabaseHealth,
    check_database_connection,
    configure_database,
    create_all_tables,
    database_transaction,
    dispose_database,
    drop_all_tables,
    get_database_health,
    reset_database,
)
from vibe_bt_03.database.api.types import (
    AssetInput,
    AssetView,
    CalendarSessionInput,
    CalendarSessionView,
    FutureDailyBarInput,
    FutureDailyBarView,
    InstrumentInput,
    InstrumentView,
    SaveResult,
    StockAdjustedBarInput,
    StockDailyBarInput,
    StockDailyBarView,
)

__all__ = [
    "AssetInput",
    "AssetView",
    "CalendarSessionInput",
    "CalendarSessionView",
    "DatabaseHealth",
    "FutureDailyBarInput",
    "FutureDailyBarView",
    "InstrumentInput",
    "InstrumentView",
    "SaveResult",
    "StockAdjustedBarInput",
    "StockDailyBarInput",
    "StockDailyBarView",
    "check_database_connection",
    "configure_database",
    "create_all_tables",
    "database_transaction",
    "dispose_database",
    "drop_all_tables",
    "get_database_health",
    "reset_database",
]
